include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - build/**
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    prefer_const_constructors: true
    avoid_print: true

